# Generated by Django 2.2.19 on 2022-05-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
