# Generated by Django 2.2.19 on 2022-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220520_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/', verbose_name='Картинка'),
        ),
    ]
